# Generated by Django 5.1.3 on 2026-05-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_fix_dateproposal_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512, unique=True)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('size', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stored media',
                'verbose_name_plural': 'stored media',
            },
        ),
    ]
