# Generated by Django 5.1.3 on 2026-05-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0008_stored_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='final_video_url',
            field=models.URLField(blank=True, default='', help_text='Optional direct MP4 link if the file is too large to upload on Vercel.'),
        ),
    ]
