# Generated by Django 5.1.3 on 2026-05-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0009_final_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='ask_gift_video',
            field=models.FileField(blank=True, help_text='Tiny looping gift video for the ask card (replaces GIF emoji).', null=True, upload_to='site/gift/'),
        ),
    ]
