# Generated by Django 5.1.3 on 2026-05-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0011_invite_private_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='personal_ask_title',
            field=models.CharField(blank=True, default='', help_text='Optional custom question just for this person. Use {name}. Leave blank for the shared template.', max_length=200),
        ),
        migrations.AlterField(
            model_name='invite',
            name='personal_note',
            field=models.TextField(blank=True, default='', help_text='Optional P.S. just for this person on the final page.'),
        ),
    ]
