# Generated by Django 5.1.3 on 2026-05-31 11:18

import django.db.models.deletion
import proposal.models
from django.db import migrations, models

CONTENT_FIELD_NAMES = [
    'ask_title', 'ask_yes_button', 'ask_no_button', 'no_runaway_messages',
    'yay_title', 'yay_subtitle', 'yay_button',
    'food_title', 'food_button',
    'schedule_title', 'schedule_date_label', 'schedule_time_label', 'schedule_button',
    'final_title', 'final_note', 'final_video_url',
]

DEFAULT_FOODS = [
    ('pizza', 'Pizza', '🍕', 0),
    ('sushi', 'Sushi', '🍣', 1),
    ('burgers', 'Burgers', '🍔', 2),
    ('pasta', 'Pasta', '🍝', 3),
    ('tacos', 'Tacos', '🌮', 4),
    ('ramen', 'Ramen', '🍜', 5),
]

DEFAULT_TIMES = [
    '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM',
    '5:00 PM', '6:00 PM', '7:00 PM', '8:00 PM',
]


def migrate_to_per_person(apps, schema_editor):
    Invite = apps.get_model('proposal', 'Invite')
    InviteContent = apps.get_model('proposal', 'InviteContent')
    SiteContent = apps.get_model('proposal', 'SiteContent')
    FoodOption = apps.get_model('proposal', 'FoodOption')
    TimeSlot = apps.get_model('proposal', 'TimeSlot')

    site = SiteContent.objects.first()
    global_foods = list(
        FoodOption.objects.filter(invite__isnull=True).order_by('order', 'label')
    )
    global_times = list(
        TimeSlot.objects.filter(invite__isnull=True).order_by('order', 'label')
    )

    for invite in Invite.objects.all():
        defaults = {}
        if site:
            for field in CONTENT_FIELD_NAMES:
                defaults[field] = getattr(site, field, '') or ''

        personal_ask = getattr(invite, 'personal_ask_title', '') or ''
        personal_note = getattr(invite, 'personal_note', '') or ''
        if personal_ask.strip():
            defaults['ask_title'] = personal_ask.strip()
        if personal_note.strip():
            defaults['final_note'] = personal_note.strip()

        InviteContent.objects.get_or_create(invite=invite, defaults=defaults)

        if not FoodOption.objects.filter(invite=invite).exists():
            if global_foods:
                for item in global_foods:
                    FoodOption.objects.create(
                        invite=invite,
                        slug=item.slug,
                        label=item.label,
                        emoji=item.emoji,
                        order=item.order,
                        is_active=item.is_active,
                        image=item.image,
                    )
            else:
                for slug, label, emoji, order in DEFAULT_FOODS:
                    FoodOption.objects.create(
                        invite=invite,
                        slug=slug,
                        label=label,
                        emoji=emoji,
                        order=order,
                    )

        if not TimeSlot.objects.filter(invite=invite).exists():
            if global_times:
                for item in global_times:
                    TimeSlot.objects.create(
                        invite=invite,
                        label=item.label,
                        order=item.order,
                        is_active=item.is_active,
                    )
            else:
                for i, label in enumerate(DEFAULT_TIMES):
                    TimeSlot.objects.create(invite=invite, label=label, order=i)

    FoodOption.objects.filter(invite__isnull=True).delete()
    TimeSlot.objects.filter(invite__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0012_invite_personal_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodoption',
            name='invite',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='food_options',
                to='proposal.invite',
            ),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='invite',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='time_slots',
                to='proposal.invite',
            ),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='invites/food/'),
        ),
        migrations.AlterField(
            model_name='foodoption',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='ask_gift_video',
            field=models.FileField(blank=True, null=True, upload_to='site/gift/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='final_title',
            field=models.CharField(
                default="glad you didn't say no. be ready by {time}, I'm coming to get you 🚗",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='final_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='her_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='no_runaway_messages',
            field=models.TextField(
                blank=True,
                default='please {name}...\n{name} wait 🥺\npretty please {name}?\nplease say yes 💗',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='foodoption',
            unique_together={('invite', 'slug')},
        ),
        migrations.CreateModel(
            name='InviteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_title', models.CharField(default='🌸 Will you go on a date with me? 🌸', max_length=200)),
                ('ask_yes_button', models.CharField(default='YES 💗', max_length=50)),
                ('ask_no_button', models.CharField(default='no... 🙈', max_length=50)),
                ('ask_gift_video', models.FileField(blank=True, null=True, upload_to='invites/gift/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='invites/backgrounds/')),
                ('no_runaway_messages', models.TextField(
                    blank=True,
                    default='please {name}...\n{name} wait 🥺\npretty please {name}?\nplease say yes 💗',
                )),
                ('yay_title', models.CharField(default='WAIT YOU ACTUALLY SAID YES?? 😭', max_length=200)),
                ('yay_subtitle', models.CharField(default='I was so ready for you to say no 😂', max_length=200)),
                ('yay_button', models.CharField(default='okay okay! →', max_length=50)),
                ('yay_image', models.ImageField(blank=True, null=True, upload_to='invites/yay/')),
                ('food_title', models.CharField(default='What are we feeling? 🍜✨', max_length=200)),
                ('food_button', models.CharField(default='this one! →', max_length=50)),
                ('schedule_title', models.CharField(default='So... when are you free?', max_length=200)),
                ('schedule_date_label', models.CharField(default='Pick a Day ✨', max_length=100)),
                ('schedule_time_label', models.CharField(default='Pick a Time ✨', max_length=100)),
                ('schedule_button', models.CharField(default='set the date! 💌', max_length=50)),
                ('final_title', models.CharField(
                    default="glad you didn't say no. be ready by {time}, I'm coming to get you 🚗",
                    max_length=300,
                )),
                ('final_note', models.TextField(
                    default='P.S. normal people text. I made a website. during lunch. for you. no big deal.',
                )),
                ('final_profile_image', models.ImageField(blank=True, null=True, upload_to='invites/profile/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='invites/videos/')),
                ('final_video_url', models.URLField(blank=True, default='')),
                ('final_video_poster', models.ImageField(blank=True, null=True, upload_to='invites/posters/')),
                ('invite', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='content',
                    to='proposal.invite',
                )),
            ],
            bases=(proposal.models.ContentMixin, models.Model),
        ),
        migrations.RunPython(migrate_to_per_person, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='invite',
            name='personal_ask_title',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='personal_note',
        ),
    ]
