# Generated by Django 5.1.3 on 2026-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0013_per_person_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecontent',
            name='ask_gift_image',
            field=models.ImageField(blank=True, null=True, upload_to='invites/gift/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='no_runaway_messages',
            field=models.TextField(blank=True, default='please {name}...\n{name} wait 🥺\npretty please {name}?\nplease {name} say yes 💗'),
        ),
    ]
